apiVersion: v1
kind: Template
labels:
  template: cart-service-jdg-cache
metadata:
  name: cart-service-jdg-cache
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Hot Rod service.
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hotrod
  spec:
    ports:
    - port: 11333
      targetPort: 11333
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=${APPLICATION_NAME}
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INFINISPAN_CONNECTORS
            value: ${INFINISPAN_CONNECTORS}
          - name: CACHE_NAMES
            value: ${CACHE_NAMES}
          - name: CACHE_TYPE_DEFAULT
            value: ${CACHE_TYPE_DEFAULT}
          - name: HOTROD_SERVICE_NAME
            value: ${APPLICATION_NAME}-hotrod
          - name: JGROUPS_CLUSTER_PASSWORD
            value: ${JGROUPS_CLUSTER_PASSWORD}
          - name: CART_CACHE_MODE
            value: ${CART_CACHE_MODE}
          - name: CART_CACHE_STATISTICS
            value: ${CART_CACHE_STATISTICS}
          - name: CART_CACHE_OWNERS
            value: ${CART_CACHE_OWNERS}
          - name: CART_CACHE_EXPIRATION_LIFESPAN
            value: ${CART_CACHE_EXPIRATION_LIFESPAN}
          - name: CART_CACHE_EVICTION_STRATEGY
            value: ${CART_CACHE_EVICTION_STRATEGY}
          - name: CART_CACHE_EVICTION_MAX_ENTRIES
            value: ${CART_CACHE_EVICTION_MAX_ENTRIES}
          - name: PRODUCT_CACHE_MODE
            value: ${PRODUCT_CACHE_MODE}
          - name: PRODUCT_CACHE_STATISTICS
            value: ${PRODUCT_CACHE_STATISTICS}
          - name: PRODUCT_CACHE_OWNERS
            value: ${PRODUCT_CACHE_OWNERS}
          - name: PRODUCT_CACHE_EVICTION_STRATEGY
            value: ${PRODUCT_CACHE_EVICTION_STRATEGY}
          - name: PRODUCT_CACHE_EVICTION_MAX_ENTRIES
            value: ${PRODUCT_CACHE_EVICTION_MAX_ENTRIES}
          - name: PRODUCT_CACHE_EXPIRATION_LIFESPAN
            value: ${PRODUCT_CACHE_EXPIRATION_LIFESPAN}
          - name: PRODUCT_CACHE_EXPIRATION_INTERVAL
            value: ${PRODUCT_CACHE_EXPIRATION_INTERVAL}
          image: jboss-datagrid71-openshift
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/datagrid/bin/livenessProbe.sh
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          - containerPort: 11211
            name: memcached
            protocol: TCP
          - containerPort: 11222
            name: hotrod-internal
            protocol: TCP
          - containerPort: 11333
            name: hotrod
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/datagrid/bin/readinessProbe.sh
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: jboss-datagrid71-openshift:1.2
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: datagrid-app
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Comma-separated list of connector types that should be configured (defaults
    to 'memcached,hotrod,rest')
  displayName: Infinispan Connectors
  name: INFINISPAN_CONNECTORS
  value: hotrod
- description: Comma-separated list of caches to configure.  By default, a distributed-cache,
    with a mode of SYNC will be configured for each entry.
  displayName: Cache Names
  name: CACHE_NAMES
  value: cart,product
- description: Default cache type for all caches. If empty then distributed will be the default.
  displayName: Default Cache Type
  name: CACHE_TYPE_DEFAULT
  value: distributed
- description: JGroups cluster password
  displayName: JGroups Cluster Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: JGROUPS_CLUSTER_PASSWORD
  required: true
- description: Clustered cache mode.
  displayName: Clustered cache mode.
  name: CART_CACHE_MODE
  value: SYNC
- description: Determines whether or not the cache collects statistics. Disable for optimal performance.
  displayName: Cache statistics.
  name: CART_CACHE_STATISTICS
  value: 'false'
- description: Number of cluster-wide replicas for each cache entry.
  displayName: Number of cluster-wide replicas.
  name: CART_CACHE_OWNERS
  value: '2'
- description: Maximum lifespan, in milliseconds, of a cache entry.
  displayName: Maximum lifespan, in milliseconds, of a cache entry.
  name: CART_CACHE_EXPIRATION_LIFESPAN
  value: '-1'
- description: Cache eviction strategy.
  displayName: Cache eviction strategy.
  name: CART_CACHE_EVICTION_STRATEGY
  value: LRU
- description: Maximum number of entries in a cache instance.
  displayName: Maximum number of entries in a cache instance.
  name: CART_CACHE_EVICTION_MAX_ENTRIES
  value: '10000'
- description: Clustered cache mode.
  displayName: Clustered cache mode.
  name: PRODUCT_CACHE_MODE
  value: SYNC
- description: Determines whether or not the cache collects statistics. Disable for optimal performance.
  displayName: Cache statistics.
  name: PRODUCT_CACHE_STATISTICS
  value: 'false'
- description: Number of cluster-wide replicas for each cache entry.
  displayName: Number of cluster-wide replicas.
  name: PRODUCT_CACHE_OWNERS
  value: '2'
- description: Maximum lifespan, in milliseconds, of a cache entry.
  displayName: Maximum lifespan, in milliseconds, of a cache entry.
  name: PRODUCT_CACHE_EXPIRATION_LIFESPAN
  value: '-1'
- description: Cache eviction strategy.
  displayName: Cache eviction strategy.
  name: PRODUCT_CACHE_EVICTION_STRATEGY
  value: LRU
- description: Maximum number of entries in a cache instance.
  displayName: Maximum number of entries in a cache instance.
  name: PRODUCT_CACHE_EVICTION_MAX_ENTRIES
  value: '10000'
- description: Maximum lifespan, in milliseconds, of a cache entry.
  displayName: Maximum lifespan, in milliseconds, of a cache entry.
  name: PRODUCT_CACHE_EXPIRATION_LIFESPAN
  value: '-1'
- description: Interval, in milliseconds, between subsequent runs to purge expired entries.
  displayName: Interval, in milliseconds, between subsequent runs to purge expired entries..
  name: PRODUCT_CACHE_EXPIRATION_INTERVAL
  value: '120000'